export const htmlCourseStructure = [
  {
    id: 1,
    title: "HTML পরিচিতি",
    description: "ওয়েব ডেভেলপমেন্টের ভিত্তি",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 1, title: "HTML কী এবং কেন?", completed: false },
      { id: 2, title: "HTML ডকুমেন্ট স্ট্রাকচার", completed: false },
      { id: 3, title: "প্রথম HTML পেজ তৈরি", completed: false },
      { id: 4, title: "HTML ট্যাগ এবং এলিমেন্ট", completed: false },
    ],
  },
  {
    id: 2,
    title: "HTML বেসিক এলিমেন্ট",
    description: "মৌলিক HTML ট্যাগসমূহ",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 5, title: "হেডিং (h1-h6) এবং প্যারাগ্রাফ", completed: false },
      { id: 6, title: "লিংক (a ট্যাগ) এবং নেভিগেশন", completed: false },
      { id: 7, title: "ইমেজ (img ট্যাগ) এবং অ্যাট্রিবিউট", completed: false },
      { id: 8, title: "লিস্ট (ul, ol, li)", completed: false },
    ],
  },
  {
    id: 3,
    title: "HTML অ্যাট্রিবিউট",
    description: "এলিমেন্টের বৈশিষ্ট্য নিয়ন্ত্রণ",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 9, title: "কমন অ্যাট্রিবিউট (id, class, style)", completed: false },
      { id: 10, title: "টাইটেল এবং Alt অ্যাট্রিবিউট", completed: false },
      { id: 11, title: "ডেটা অ্যাট্রিবিউট", completed: false },
      { id: 12, title: "প্রজেক্ট: সিম্পল ওয়েবপেজ", completed: false },
    ],
  },
  {
    id: 4,
    title: "HTML টেক্সট ফরম্যাটিং",
    description: "টেক্সট স্টাইলিং এবং ফরম্যাটিং",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 13, title: "বোল্ড, ইটালিক, আন্ডারলাইন", completed: false },
      { id: 14, title: "সুপারস্ক্রিপ্ট এবং সাবস্ক্রিপ্ট", completed: false },
      { id: 15, title: "কোটেশন এবং সাইটেশন", completed: false },
      { id: 16, title: "প্রি-ফরম্যাটেড টেক্সট", completed: false },
    ],
  },
  {
    id: 5,
    title: "HTML টেবিল",
    description: "ডেটা টেবিল তৈরি এবং স্টাইলিং",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 17, title: "বেসিক টেবিল স্ট্রাকচার", completed: false },
      { id: 18, title: "টেবিল হেডার এবং ক্যাপশন", completed: false },
      { id: 19, title: "সেল মার্জিং (colspan, rowspan)", completed: false },
      { id: 20, title: "টেবিল স্টাইলিং এবং বর্ডার", completed: false },
    ],
  },
  {
    id: 6,
    title: "HTML ফর্ম - পার্ট ১",
    description: "ইউজার ইনপুট সংগ্রহ",
    duration: "২ সপ্তাহ",
    lessons: [
      { id: 21, title: "ফর্ম এলিমেন্ট এবং স্ট্রাকচার", completed: false },
      { id: 22, title: "ইনপুট টাইপ (text, email, password)", completed: false },
      { id: 23, title: "টেক্সটএরিয়া এবং সিলেক্ট", completed: false },
      { id: 24, title: "চেকবক্স এবং রেডিও বাটন", completed: false },
    ],
  },
  {
    id: 7,
    title: "HTML ফর্ম - পার্ট ২",
    description: "অ্যাডভান্সড ফর্ম এলিমেন্ট",
    duration: "১ সপ্তাহ",
    lessons: [
      {
        id: 25,
        title: "HTML5 ইনপুট টাইপ (date, number, range)",
        completed: false,
      },
      { id: 26, title: "ফর্ম ভ্যালিডেশন", completed: false },
      { id: 27, title: "ফাইল আপলোড এবং হিডেন ফিল্ড", completed: false },
      { id: 28, title: "প্রজেক্ট: কন্ট্যাক্ট ফর্ম", completed: false },
    ],
  },
  {
    id: 8,
    title: "HTML মাল্টিমিডিয়া",
    description: "অডিও, ভিডিও এবং ইমেজ",
    duration: "১ সপ্তাহ",
    lessons: [
      {
        id: 29,
        title: "ইমেজ অপটিমাইজেশন এবং রেসপন্সিভ ইমেজ",
        completed: false,
      },
      { id: 30, title: "অডিও এলিমেন্ট এবং কন্ট্রোল", completed: false },
      { id: 31, title: "ভিডিও এলিমেন্ট এবং সোর্স", completed: false },
      {
        id: 32,
        title: "ইউটিউব এবং এক্সটার্নাল মিডিয়া এম্বেড",
        completed: false,
      },
    ],
  },
  {
    id: 9,
    title: "HTML সিমান্টিক এলিমেন্ট",
    description: "HTML5 সিমান্টিক ট্যাগ",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 33, title: "header, nav, main, footer", completed: false },
      { id: 34, title: "section, article, aside", completed: false },
      { id: 35, title: "figure, figcaption, time", completed: false },
      {
        id: 36,
        title: "প্রজেক্ট: সিমান্টিক ওয়েবসাইট লেআউট",
        completed: false,
      },
    ],
  },
  {
    id: 10,
    title: "HTML মেটা ট্যাগ এবং SEO",
    description: "সার্চ ইঞ্জিন অপটিমাইজেশন",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 37, title: "মেটা ট্যাগের পরিচিতি", completed: false },
      { id: 38, title: "SEO এর জন্য মেটা ট্যাগ", completed: false },
      { id: 39, title: "ওপেন গ্রাফ এবং সোশ্যাল মিডিয়া", completed: false },
      { id: 40, title: "ফেভিকন এবং অ্যাপ আইকন", completed: false },
    ],
  },
  {
    id: 11,
    title: "HTML অ্যাক্সেসিবিলিটি",
    description: "সবার জন্য ওয়েব",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 41, title: "অ্যাক্সেসিবিলিটির গুরুত্ব", completed: false },
      { id: 42, title: "ARIA অ্যাট্রিবিউট", completed: false },
      { id: 43, title: "কীবোর্ড নেভিগেশন", completed: false },
      { id: 44, title: "স্ক্রিন রিডার সাপোর্ট", completed: false },
    ],
  },
  {
    id: 12,
    title: "HTML এবং CSS ইন্টিগ্রেশন",
    description: "স্টাইলিং এর সাথে HTML",
    duration: "১ সপ্তাহ",
    lessons: [
      {
        id: 45,
        title: "ইনলাইন, ইন্টার্নাল এবং এক্সটার্নাল CSS",
        completed: false,
      },
      { id: 46, title: "CSS সিলেক্টর এবং HTML ক্লাস", completed: false },
      { id: 47, title: "রেসপন্সিভ ডিজাইনের জন্য HTML", completed: false },
      { id: 48, title: "CSS ফ্রেমওয়ার্ক ইন্টিগ্রেশন", completed: false },
    ],
  },
  {
    id: 13,
    title: "HTML বেস্ট প্র্যাকটিস",
    description: "প্রফেশনাল HTML কোডিং",
    duration: "১ সপ্তাহ",
    lessons: [
      { id: 49, title: "ক্লিন কোড এবং ইন্ডেন্টেশন", completed: false },
      { id: 50, title: "পারফরম্যান্স অপটিমাইজেশন", completed: false },
      { id: 51, title: "ক্রস-ব্রাউজার কম্প্যাটিবিলিটি", completed: false },
      { id: 52, title: "HTML ভ্যালিডেশন", completed: false },
    ],
  },
  {
    id: 14,
    title: "ফাইনাল প্রজেক্ট: কমপ্লিট ওয়েবসাইট",
    description: "সব কিছু একসাথে ব্যবহার",
    duration: "২ সপ্তাহ",
    lessons: [
      { id: 53, title: "প্রজেক্ট প্ল্যানিং এবং স্ট্রাকচার", completed: false },
      { id: 54, title: "হোমপেজ এবং নেভিগেশন", completed: false },
      { id: 55, title: "কন্টেন্ট পেজ এবং ফর্ম", completed: false },
      { id: 56, title: "ফাইনাল টেস্টিং এবং ডিপ্লয়মেন্ট", completed: false },
    ],
  },
];
